/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author anoop
 */
public class Login extends javax.swing.JFrame {

   Connection con = null;
   PreparedStatement ps = null;
   ResultSet rs = null;
   
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Text_uname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Text_upass = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-enter-filled-50.png"))); // NOI18N
        jLabel1.setText(" username :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 280, 90));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-password-filled-50.png"))); // NOI18N
        jLabel2.setText(" password :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 270, 120));

        Text_uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_unameActionPerformed(evt);
            }
        });
        getContentPane().add(Text_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 194, 33));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-arrow-filled-50.png"))); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 260, 46));

        Text_upass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Text_upass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_upassActionPerformed(evt);
            }
        });
        getContentPane().add(Text_upass, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 194, 35));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 520, 250));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Hektor_hostel_triple_room.jpg"))); // NOI18N
        jLabel4.setText("hos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -10, 1340, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        con = Sqlconnect.connectDB();
        String  sql = "Select uname,upass from users where uname=? and upass=?";
        
        
        try{
            ps = con.prepareStatement(sql);
            ps.setString(1,Text_uname.getText());
            ps.setString(2,Text_upass.getText());
            rs = ps.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null,"welcome user");
                Home hm = new Home();
                hm.setVisible(true);
                setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null,"invalid username or password","Access denied " ,JOptionPane.ERROR_MESSAGE);
                
            }
        }
        catch(Exception ex){ 
            
            JOptionPane.showMessageDialog(null,ex);
            
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void Text_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_unameActionPerformed

    private void Text_upassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_upassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_upassActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Text_uname;
    private javax.swing.JPasswordField Text_upass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
